return {}
-- return {
--   'lukas-reineke/indent-blankline.nvim',
--   ---@module 'ibl'
--   --- @type ibl.config
--   opts = {
--     indent = {
--       char = '│',
--       tab_char = '│',
--       -- highlight = 'IndentBlanklineChar',
--       -- highlight = { 'Function', 'Label' },
--     },
--     scope = {
--       enabled = true,
--       show_start = true,
--       show_end = true,
--       highlight = { 'Function', 'Label' },
--     },
--     exclude = {
--       filetypes = {
--         'help',
--         'alpha',
--         'dashboard',
--         'neo-tree',
--         'Trouble',
--         'trouble',
--         'lazy',
--         'mason',
--         'notify',
--         'toggleterm',
--         'lazyterm',
--       },
--     },
--   },
--   main = 'ibl',
-- }
